-- تعطيل قواعد الأمان (RLS) مؤقتاً للتأكد من أن المشكلة ليست منها
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE safety_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE po_budgets DISABLE ROW LEVEL SECURITY;
ALTER TABLE salary_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE escalations DISABLE ROW LEVEL SECURITY;
ALTER TABLE permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE po_acceptances DISABLE ROW LEVEL SECURITY;
ALTER TABLE fin_config DISABLE ROW LEVEL SECURITY;
